---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./core/vault/install"
  prune: true
  wait: false
  postBuild:
    substitute:
      vault_chart_version: "0.12.3"
