---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./core/istio/install"
  prune: true
  wait: true
  postBuild:
    substitute:
      istio_version: "1.21.*"
