---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  targetNamespace: vault
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "${vault_chart_version}"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  releaseName: vault
  install:
    createNamespace: true
