---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-es
  namespace: nextcloud
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: nextcloud
    kind: SecretStore
  target:
    name: nextcloud-admin
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: apps/nextcloud/admin
        property: nextcloud-username
    - secretKey: nextcloud-password
      remoteRef:
        key: apps/nextcloud/admin
        property: nextcloud-password
