---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: apps
      version: v2
      auth:
        kubernetes:
          mountPath: k8s
          role: reader
          serviceAccountRef:
            name: vault-server
