---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-second
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/nextcloud/second"
  dependsOn:
    - name: nextcloud-first
  prune: true
  wait: true
