---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingress-gw
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: "${istio_version}"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  releaseName: istio-ingress-gw
  dependsOn:
    - name: istiod
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: http-gw
  namespace: istio-system
spec:
  selector:
    istio: ingress-gw
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - nc.nuc-server.nucnet
    - qb.nuc-server.nucnet
