---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingress-gw
  namespace: flux-system
  targetNamespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istio/gateway
      version: "${istio_version}"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: istio-ingress-gw
  dependsOn:
    - name: istiod
