---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: "${istio_version}"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  releaseName: istiod
  dependsOn:
    - name: istio-base
