---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  targetNamespace: nextcloud
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: "4.6.4"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  releaseName: nextcloud

  values:
    nextcloud:
      host: nc.nuc-server.nucnet
      existingSecret:
        enabled: true
        secretName: nextcloud-admin

    externalDatabase:
      enabled: true
      existingSecret:
        enabled: true
        secretName: mariadb-admin
        passwordKey: mariadb-password

    mariadb:
      enabled: true
      auth:
        existingSecret: mariadb-admin
      primary:
        persistence:
          enabled: true
          size: 100Gi

    persistence:
      enabled: true
      storageClass: local-path
      size: 500Gi
